# permissions for end users to edit namespacemonitors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: namespacemonitor
    app.kubernetes.io/managed-by: kustomize
  name: namespacemonitor-editor-role
rules:
- apiGroups:
  - monitoring.resource.com
  resources:
  - namespacemonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.resource.com
  resources:
  - namespacemonitors/status
  verbs:
  - get
