apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: namespacemonitor
    app.kubernetes.io/managed-by: kustomize
  name: namespacemonitor-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: namespacemonitor-leader-election-role
subjects:
- kind: ServiceAccount
  name: namespacemonitor-controller-manager
  namespace: {{ .Release.Namespace }}
