apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: namespacemonitor
    app.kubernetes.io/managed-by: kustomize
  name: namespacemonitor-controller-manager
  namespace: {{ .Release.Namespace }}
